server:
  port: 8080

spring:
  application:
    name: flight-status-api

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  api-docs:
    path: /v3/api-docs

logging:
  level:
    root: INFO
    com.columbus.flightstatus: DEBUG

app:
  refresh-interval: 10000